name: Features Branch CI

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'support/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B clean verify -s settings.xml -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
